name: Zip
description: Zip Folder/Files
inputs:
  files:
    description: "Files to zip"
    required: true
  output:
    description: "Zip filename (NO EXTENSION)"
    required: true
  context:
    description: Working Directory
    required: false
    default: .
outputs:
  filename:
    description: "Zip file (NO EXTENSION)"
    value: ${{ steps.zip.outputs.filename }}
runs:
  using: composite
  steps:
    - id: zip
      name: Zip Files
      shell: bash
      run: |
        # Prepare files list
        FILES=$(echo ${{ inputs.files }} | tr "," "\n" | xargs)
        ZIP_FILE="${{ inputs.output }}"

        cd ${{ inputs.context }}
        zip -qq -r "${ZIP_FILE}.zip" $FILES

        echo "::debug::$(unzip -l "${ZIP_FILE}.zip")"
        echo "filename=$ZIP_FILE" >> $GITHUB_OUTPUT;
