name: "Setup Git"
description: "Setup Git"

inputs:
  bot-name:
    required: true
    description: "Your GH App name"
  bot-id:
    required: true
    description: "Your App ID"

outputs:
  email:
    value: ${{ steps.identity.outputs.email }}
    description: "Git Email"
  username:
    value: ${{ steps.identity.outputs.username }}
    description: "Git Username"

runs:
  using: "composite"
  steps:
    - name: Setup git identity as bot
      id: identity
      shell: bash
      run: |
        username="${{ inputs.bot-name }}[bot]"
        email="${{ inputs.bot-id }}+${username}@users.noreply.github.com"

        git config --global user.name "$username"
        git config --global user.email "$email"

        echo "username=$username" >> $GITHUB_OUTPUT
        echo "email=$email" >> $GITHUB_OUTPUT
