name: "Setup Git"
description: "Setup Git"

outputs:
  email:
    value: ${{ steps.identity.outputs.email }}
    description: "Git Email"
  username:
    value: ${{ steps.identity.outputs.username }}
    description: "Git Username"

runs:
  using: "composite"
  steps:
    - name: Setup git identity as bot
      id: identity
      shell: bash
      run: |
        username="Aquacloud Bot"
        email="bot@aquacloud.it"

        git config --global user.email "$email"
        git config --global user.name "$username"

        echo "username=$username" >> $GITHUB_OUTPUT
        echo "email=$email" >> $GITHUB_OUTPUT
