name: "Setup Git"
description: "Setup Git"

inputs:
  BOT_NAME:
    required: false
    description: "Your GH App name"
    default: "aquacloud-bot"
  BOT_ID:
    required: true
    description: "Your App ID"

outputs:
  email:
    value: ${{ steps.identity.outputs.email }}
    description: "Git Email"
  username:
    value: ${{ steps.identity.outputs.username }}
    description: "Git Username"

runs:
  using: "composite"
  steps:
    - name: Setup git identity as bot
      id: identity
      shell: bash
      run: |
        bot_name="${{ inputs.BOT_NAME }}"
        username="$bot_name[bot]"
        bot_id="${{ inputs.BOT_ID }}"
        email="$bot_id+$username@users.noreply.github.com"

        git config --global user.email "$email"
        git config --global user.name "$username"

        echo "username=$username" >> $GITHUB_OUTPUT
        echo "email=$email" >> $GITHUB_OUTPUT
