name: "Setup JDK"
description: "Setup JDK + Cache"

inputs:
  java-version:
    description: "Java Version"
    default: "17"
    required: false
  server-id:
    description: "Server ID"
    default: "github"
    required: false
  server-username:
    description: "Server username"
    required: true
  server-password:
    description: "Server password"
    required: true

runs:
  using: composite
  steps:
    - name: "Setup Java"
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        cache: "maven"
        server-id: ${{ inputs.server-id }}
        server-username: ${{ inputs.server-username }}
        server-password: ${{ inputs.server-password }}

    - uses: actions/cache@v1
      with:
        path: "~/.m2/repository"
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          ${{ runner.os }}-maven-
          maven-
