name: "Docker Build"
description: "An action to perform docker build"

inputs:
  labels:
    description: "Docker labels"
    required: false
  tags:
    description: "Tags to build"
    required: true
  build-args:
    description: "Build args"
    required: false
  push:
    description: "Wether to push the docker image or nto"
    default: "true"
    required: false
  registry-url:
    description: "Registry URL"
    required: true

runs:
  using: composite
  steps:
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2
    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry-url }}
    - name: Build Docker Image
      uses: docker/build-push-action@v4
      with:
        push: ${{ inputs.push == 'true' }}
        tags: ${{ inputs.tags }}
        build-args: ${{ inputs.build-args }}
        labels: ${{ inputs.labels }}
