name: "Git Tag"
description: "Push a git tag"

inputs:
  tag:
    description: "TAG"
    required: true

outputs:
  released:
    description: "Wether the tag has been published or not"
    value: ${{ steps.tag.outputs.released }}
  commit:
    description: "Commit hash"
    value: ${{ steps.tag.outputs.commit }}

runs:
  using: composite
  steps:
    - name: "Git Tag"
      id: tag
      shell: bash
      run: |
        TAG="${{ inputs.tag }}"

        git tag $TAG -m "Release $TAG"
        git push origin $TAG

        commit=$(git log -1 --format=%H)

        echo "released=true" >> $GITHUB_OUTPUT
        echo "commit=$commit" >> $GITHUB_OUTPUT
