name: Download S3 Artifact
description: "Download an artifact from S3"
inputs:
  bucket:
    description: "S3 bucket"
    required: true
  aws_region:
    description: "S3 region"
    required: true
  aws_access_key_id:
    description: "AWS Access Key ID"
    required: true
  aws_secret_access_key:
    description: "AWS Secret Access Key"
    required: true
  output:
    description: "Unzip output"
    default: "."
    required: false
  context:
    description: "Download path"
    default: "."
    required: false
  filename:
    description: "Remote zip name (NO EXTENSION)"
    required: true

runs:
  using: composite
  steps:
    - name: Download from S3
      uses: keithweaver/aws-s3-github-action@v1.0.0
      with:
        command: cp
        aws_access_key_id: ${{ inputs.aws_access_key_id }}
        aws_secret_access_key: ${{ inputs.aws_secret_access_key }}
        aws_region: ${{ inputs.aws_region }}
        source: s3://${{ inputs.bucket }}/${{ github.repository }}/${{ inputs.path }}/${{ inputs.filename }}.zip
        destination: ${{ inputs.context }}/${{ inputs.filename }}.zip
    - name: Unzip
      shell: bash
      run: |
        cd ${{ inputs.context }}
        unzip -qq ${{ inputs.filename }}.zip -d ${{ inputs.output }}
