name: "Update commit author"
description: "Given commit hash, update the author to the owner of the current GITHUB_TOKEN"

inputs:
  commit_hash:
    description: "Commit Hash"
    required: true
  repo:
    required: true
    description: "Repository <owner/name>"

runs:
  using: composite
  steps:
    - name: Run Script
      id: script
      shell: bash
      if: ${{ inputs.commit_hash != '' }}
      run: |
        ${{ github.action_path }}script.sh "${{ inputs.commit_hash }}" "${{ inputs.repo }}" "${{ env.GITHUB_TOKEN }}"
