name: "Get Repo Metadata"
description: "Retrive repository metadata"

outputs:
  metadata:
    description: "Repository metadata"
    value: ${{ fromJson(steps.get-metadata.outputs.result) }}

runs:
  using: composite
  steps:
    - name: Get Metadata
      id: get-metadata
      uses: actions/github-script@v3
      with:
        script: |
          const repo = await github.repos.get(context.repo)
          return repo.data
