name: "Get Build Number"
description: "Get Build Number"

outputs:
  tag:
    description: "Next Tag"
    value: ${{ steps.next-number.outputs.tag }}

runs:
  using: composite
  steps:
    - name: Get Build Number
      id: next-number
      shell: bash
      run: |
        git pull --tags

        BRANCH_NAME=${GITHUB_REF##*/}
        BRANCH_NAME=${BRANCH_NAME//\//-}
        BUILD_NUMBER=$(git tag | sort --version-sort | grep "$BRANCH_NAME" | tail -n 1 | awk -F. '{print $2}')

        # Trim
        BUILD_NUMBER=$(echo "${BUILD_NUMBER}" | xargs echo -n)

        if [ -z "$BUILD_NUMBER" ]; then 
          BUILD_NUMBER=1
        else
          BUILD_NUMBER=$(( BUILD_NUMBER + 1 ))
        fi

        TAG="$BRANCH_NAME.$BUILD_NUMBER"

        echo "TAG=$TAG"

        echo "tag=$TAG" >> $GITHUB_OUTPUT
