name: "Get Build Number"
description: "Get Build Number"

outputs:
  tag:
    description: "Next Tag"
    value: ${{ steps.next-number.outputs.tag }}

runs:
  using: composite
  steps:
    - id: next-number
      name: Get Build Number
      shell: bash
      run: script.sh
