name: "Get Build Number"
description: "Get Build Number"

author: "Federico Vitale <federico.vitale@aquacloud.it>"

outputs:
  tag:
    description: "Next Tag"

runs:
  using: "docker"
  image: "Dockerfile"
