name: "Standard Version"
description: "Standard Version"

inputs:
  pre-release:
    required: false
    description: "Prerelease"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.pre-release }}
