name: "Helm"
description: "Update version and release helm package"
author: "Federico Vitale <federico.vitale@aquacloud.it>"

inputs:
  version:
    required: true
    description: "Version to release"
  repo:
    required: true
    description: "Repository"
  commit_user_email:
    description: "Commit Email"
    required: false
    default: "bot@aquacloud.it"
  commit_user_name:
    description: "Commit username"
    required: false
    default: "Aquacloud Bot"
  token:
    description: "Github Token"
    required: true

runs:
  using: composite
  steps:
    - name: Helm Installation
      uses: azure/setup-helm@v1.1
      with:
        version: v3.7.0
        token: ${{ inputs.token }}

    - name: Helm Repository Checkout
      uses: actions/checkout@v2
      with:
        repository: ${{ inputs.repo }}
        token: ${{ inputs.token }}
        fetch-depth: 0
        persist-credentials: true
        ref: main
        path: helm

    - name: Update Chart.version
      uses: fjogeleit/yaml-update-action@main
      with:
        commitChange: false
        valueFile: ".chart/Chart.yaml"
        propertyPath: "version"
        value: ${{ inputs.version }}
        message: "Update chart version to ${{ github.event.inputs.version }}"
        updateFile: true

    - name: Update Chart.appVersion
      uses: fjogeleit/yaml-update-action@main
      with:
        commitChange: false
        valueFile: ".chart/Chart.yaml"
        propertyPath: "appVersion"
        value: ${{ inputs.version }}
        message: "Update chart version to ${{ github.event.inputs.version }}"
        updateFile: true

    - name: Helm Package
      run: helm package .chart -d helm
      shell: bash

    - name: Helm Push
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ inputs.token }}
      with:
        destination_repo: ${{ inputs.repo }}
        source_file: helm/${{ github.event.repository.name }}-${{ github.event.inputs.version }}.tgz
        user_email: ${{ inputs.commit_user_email }}
        user_name: ${{ inputs.commit_user_name }}
