name: Validate Action Schema

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  validate-actions:
    name: Validate Actions
    runs-on: ubuntu-latest
    environment: validation
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install action-validator with asdf
        uses: asdf-vm/actions/install@v1
        with:
          tool_versions: |
            action-validator 0.1.2

      - name: Lint Actions
        shell: bash
        run: |
          ./${{ github.action_path }}/lint.sh

  generate-docs:
    name: Generate Docs
    if: startsWith(github.ref, 'refs/heads/main')
    runs-on: ubuntu-latest
    environment: generation
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Generator
        uses: rawnly/github-actions-autodocs@main
      - name: Setup Git
        id: identity
        uses: aquacloud-dev/github-actions/setup-git@main
      - name: Get Bot Token
        id: bot
        uses: aquacloud-dev/github-actions/get-bot-token@main
        with:
          BOT_ID: ${{ secrets.BOT_ID }}
          BOT_PEM: ${{ secrets.BOT_PEM }}
      - name: Generate
        shell: bash
        run: |
          ./${{ github.action_path }}/generate.sh
      - name: Commit
        id: commit
        uses: aquacloud-dev/github-actions/git-commit@main
        env:
          GITHUB_TOKEN: ${{ steps.bot.outputs.token }}
        with:
          message: "docs: README"
          auto_resolve_conflicts: true
      - name: Update commit author
        uses: aquacloud-dev/github-actions/update-commit-author@main
        env:
          GITHUB_TOKEN: ${{ steps.bot.outputs.token }}
        with:
          repo: aquacloud-dev/github-actions
          commit_hash: ${{ steps.commit.outputs.commit_hash }}
