name: Validate Action Schema

on:
  push:
    paths-ignore:
      - "README.md"
      - ".github/workflows"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  validate-actions:
    name: Validate Actions
    runs-on: ubuntu-latest
    environment: validation
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install action-validator with asdf
        uses: asdf-vm/actions/install@v1
        with:
          tool_versions: |
            action-validator 0.1.2

      - name: Lint Actions
        shell: bash
        env:
          GITHUB_WORKSPACE: $GITHUB_WORKSPACE
        run: |
          set -e
          .github/workflows/lint.sh

  generate-docs:
    name: Generate Docs
    if: startsWith(github.ref, 'refs/heads/main')
    runs-on: ubuntu-latest
    environment: generation
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Generator
        uses: rawnly/github-actions-autodocs@main

      - name: Setup Git
        id: identity
        uses: aquacloud-dev/github-actions/setup-git@main
        with:
          bot-name: ${{ secrets.APP_NAME }}
          bot-id: ${{ secrets.APP_ID }}

      - name: Generate
        shell: bash
        env:
          GITHUB_WORKSPACE: $GITHUB_WORKSPACE
        run: |
          set -e 
          .github/workflows/generate.sh

      - name: Commit
        id: commit
        uses: aquacloud-dev/github-actions/git-commit@main
        env:
          GITHUB_TOKEN: ${{ steps.bot.outputs.token }}
        with:
          message: "[skip ci] Updated Readme"
          auto_resolve_conflicts: true
