name: Validate Action Schema

on: [push]

defaults:
  run:
    shell: bash

jobs:
  validate-actions:
    name: Validate Actions
    runs-on: ubuntu-latest
    environment: validation
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install action-validator with asdf
        uses: asdf-vm/actions/install@v1
        with:
          tool_versions: |
            action-validator 0.1.2

      - name: Lint Actions
        shell: bash
        run: |
          for dir in */; do 
            if [ -d "$dir" ]; then 
              echo "Linting on $dir/action.yml"

              cd "$dir" || exit 
              action-validator action.yml

              cd ..
            fi
          done

  generate-docs:
    name: Generate Docs
    if: startsWith(github.ref, 'refs/heads/main')
    runs-on: ubuntu-latest
    environment: generation
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Generator
        uses: rawnly/github-actions-autodocs@main
      - name: Setup Git
        id: git
        uses: aquacloud-dev/github-actions/setup-git@main
        with:
          BOT_ID: ${{ secrets.BOT_ID }}
          BOT_PEM: ${{ secrets.BOT_PEM }}
      - name: Generate
        shell: bash
        run: |
          for dir in */; do 
            if [ -d "$dir" ]; then 
              echo "Generating on $dir action.yml"

              cd "$dir" || exit 
              github-actions-autodocs 

              cd ..
            fi
          done
      - name: Commit
        shell: bash
        env:
          GITHUB_TOKEN: ${{ steps.git.outputs.token }}
        run: |
          git add -A .
          git commit -m 'docs: readme'
          git push origin ${{ github.ref }}
