name: Validate Action Schema

on: [push]

defaults:
  run:
    shell: bash

jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install action-validator with asdf
        uses: asdf-vm/actions/install@v1
        with:
          tool_versions: |
            action-validator 0.1.2
      - name: Lint Actions
        run: action-validator "./**/action.yml"
