name: Validate Action Schema

on: [push]

defaults:
  run:
    shell: bash

jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install action-validator with asdf
        uses: asdf-vm/actions/install@v1
        with:
          tool_versions: |
            action-validator 0.1.2

      - name: Lint Actions
        shell: bash
        run: |
          for dir in */; do 
            if [ -d "$dir" ]; then 
              echo "Linting on $dir/action.yml"

              cd "$dir" || exit 
              action-validator action.yml

              cd ..
            fi
          done
